import { Company } from '../types';

export const EURONEXT_AMSTERDAM_COMPANIES: Company[] = [
  // AEX Components
  { symbol: 'AALB', name: 'AALBERTS', isin: 'NL0000852564', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'ABN', name: 'ABN AMRO BANK', isin: 'NL0011540547', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'AD', name: 'AHOLD DELHAIZE', isin: 'NL0011794037', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'ADYEN', name: 'ADYEN', isin: 'NL0012969182', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'AGN', name: 'AEGON', isin: 'NL0000303709', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'AKZA', name: 'AKZONOBEL', isin: 'NL0013267909', market: 'Euronext Amsterdam', sector: 'Materials' },
  { symbol: 'ASML', name: 'ASML', isin: 'NL0010273215', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'ASM', name: 'ASM INTERNATIONAL', isin: 'NL0000334118', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'ASRNL', name: 'ASR NEDERLAND', isin: 'NL0011872007', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'BESI', name: 'BE SEMICONDUCTOR', isin: 'NL0012866412', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'DSFIR', name: 'DSM-FIRMENICH', isin: 'CH1216478797', market: 'Euronext Amsterdam', sector: 'Materials' },
  { symbol: 'EXO', name: 'EXOR', isin: 'NL0012059018', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'HEIA', name: 'HEINEKEN', isin: 'NL0000009165', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'IMCD', name: 'IMCD', isin: 'NL0010801007', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'INGA', name: 'ING GROEP', isin: 'NL0011821202', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'KPN', name: 'KPN', isin: 'NL0011559489', market: 'Euronext Amsterdam', sector: 'Telecommunications' },
  { symbol: 'NN', name: 'NN GROUP', isin: 'NL0010773842', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'PHL', name: 'PHILIPS', isin: 'NL0000009538', market: 'Euronext Amsterdam', sector: 'Healthcare' },
  { symbol: 'PRX', name: 'PROSUS', isin: 'NL0013654783', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'RAND', name: 'RANDSTAD', isin: 'NL0000379121', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'REN', name: 'RELAX', isin: 'GB00B2B0DG97', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'SHELL', name: 'SHELL', isin: 'GB00BP6MXD84', market: 'Euronext Amsterdam', sector: 'Energy' },
  { symbol: 'SIGN', name: 'SIGNIFY', isin: 'NL0011821392', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'UMG', name: 'UNIVERSAL MUSIC', isin: 'NL0015000IY2', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'UNA', name: 'UNILEVER', isin: 'GB00B10RZP78', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'WKL', name: 'WOLTERS KLUWER', isin: 'NL0000395903', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },

  // AMX Components
  { symbol: 'AF', name: 'AIR FRANCE-KLM', isin: 'FR0000031122', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'ALFEN', name: 'ALFEN', isin: 'NL0012817175', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'ALLFG', name: 'ALLFUNDS GROUP', isin: 'GB00BNGNBV58', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'AMG', name: 'AMG CRITICAL MATERIALS', isin: 'NL0006141781', market: 'Euronext Amsterdam', sector: 'Materials' },
  { symbol: 'APER', name: 'APERAM', isin: 'LU0569974404', market: 'Euronext Amsterdam', sector: 'Materials' },
  { symbol: 'ARCAD', name: 'ARCADIS', isin: 'NL0006237562', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'BASIC', name: 'BASIC-FIT', isin: 'NL0011876321', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'CORB', name: 'CORBION', isin: 'NL0010583399', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'CTPNV', name: 'CTP', isin: 'NL00150006R6', market: 'Euronext Amsterdam', sector: 'Real Estate' },
  { symbol: 'FLOW', name: 'FLOW TRADERS', isin: 'NL0011279450', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'FUGRC', name: 'FUGRO', isin: 'NL0015000W57', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'GALN', name: 'GALAPAGOS', isin: 'BE0003851681', market: 'Euronext Amsterdam', sector: 'Healthcare' },
  { symbol: 'HAL', name: 'HAL TRUST', isin: 'BMG455841020', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'INPST', name: 'INPOST', isin: 'LU2290522684', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'JDEP', name: 'JDE PEETS', isin: 'NL0014332678', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'JUST', name: 'JUST EAT TAKEAWAY', isin: 'NL0012015749', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'OCI', name: 'OCI', isin: 'NL0010558897', market: 'Euronext Amsterdam', sector: 'Materials' },
  { symbol: 'PNL', name: 'POSTNL', isin: 'NL0009739416', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'SBMO', name: 'SBM OFFSHORE', isin: 'NL0000360618', market: 'Euronext Amsterdam', sector: 'Energy' },
  { symbol: 'TKG', name: 'TKH GROUP', isin: 'NL0000852523', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'VLK', name: 'VAN LANSCHOT KEMPEN', isin: 'NL0000302636', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'VPK', name: 'VOPAK', isin: 'NL0009432490', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'WDP', name: 'WDP', isin: 'BE0003763779', market: 'Euronext Amsterdam', sector: 'Real Estate' },
  { symbol: 'WHA', name: 'WERELDHAVE', isin: 'NL0000289213', market: 'Euronext Amsterdam', sector: 'Real Estate' },

  // AScX & Local Market (Small Caps & Obscure Funds)
  { symbol: 'ACOMO', name: 'ACOMO', isin: 'NL0000313286', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'AXS', name: 'ACCSYS TECHNOLOGIES', isin: 'GB00B1Y76Z19', market: 'Euronext Amsterdam', sector: 'Materials' },
  { symbol: 'AJAX', name: 'AFC AJAX', isin: 'NL0000332419', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'ALARI', name: 'ALARIUS', isin: 'NL0012845614', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'ALU', name: 'ALUMEXX', isin: 'NL0012240956', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'AVTX', name: 'AVANTIUM', isin: 'NL0012047823', market: 'Euronext Amsterdam', sector: 'Materials' },
  { symbol: 'BAMNB', name: 'BAM GROEP KON', isin: 'NL0000337319', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'BEVER', name: 'BEVER HOLDING', isin: 'NL0000288116', market: 'Euronext Amsterdam', sector: 'Real Estate' },
  { symbol: 'BOLS', name: 'LUCAS BOLS', isin: 'NL0010990370', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'BRILL', name: 'BRILL', isin: 'NL0000339133', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'BRNL', name: 'BRUNEL INTERNATIONAL', isin: 'NL0011440755', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'BSGR', name: 'B&S GROUP', isin: 'LU1789205884', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'CABKA', name: 'CABKA', isin: 'NL00150000S7', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'CMCOM', name: 'CM.COM', isin: 'NL0012499669', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'CTAC', name: 'CTAC', isin: 'NL0000346369', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'DELFT', name: 'PORCELEYNE FLES', isin: 'NL0000440261', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'EASE', name: 'EASE2PAY', isin: 'NL0000345619', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'EBUS', name: 'EBUSCO HOLDING', isin: 'NL0015000CZ2', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'ECMPA', name: 'EUROCOMMERCIAL PROPERTIES', isin: 'NL0000030740', market: 'Euronext Amsterdam', sector: 'Real Estate' },
  { symbol: 'ENVI', name: 'ENVIPCO', isin: 'NL00150007O1', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'FAST', name: 'FASTNED', isin: 'NL0013654809', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'FORBP', name: 'FORFARMERS', isin: 'NL0011825799', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'HEIJ', name: 'HEIJMANS', isin: 'NL0009269109', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'HYDR', name: 'HYDRATEC', isin: 'NL0000359107', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'IEX', name: 'IEX GROUP', isin: 'NL0000289130', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'KENDR', name: 'KENDRION', isin: 'NL0000381887', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'LVI', name: 'LAVIDE', isin: 'NL0006238123', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'MAREL', name: 'MAREL', isin: 'IS0000000388', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'MOTRK', name: 'MOTORK', isin: 'LU2391216962', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'NEDAP', name: 'NEDAP', isin: 'NL0000371243', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'NSI', name: 'NSI', isin: 'NL0012365050', market: 'Euronext Amsterdam', sector: 'Real Estate' },
  { symbol: 'NXFIL', name: 'NX FILTRATION', isin: 'NL0015000D50', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'ONWD', name: 'ONWARD MEDICAL', isin: 'BE0974381137', market: 'Euronext Amsterdam', sector: 'Healthcare' },
  { symbol: 'PHARM', name: 'PHARMING GROUP', isin: 'NL0010391025', market: 'Euronext Amsterdam', sector: 'Healthcare' },
  { symbol: 'SIFG', name: 'SIF HOLDING', isin: 'NL0011660485', market: 'Euronext Amsterdam', sector: 'Energy' },
  { symbol: 'SLIGR', name: 'SLIGRO FOOD GROUP', isin: 'NL0000817179', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'SNOW', name: 'SNOWWORLD', isin: 'NL0010887899', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'TOM2', name: 'TOMTOM', isin: 'NL0000387058', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'VALUE', name: 'VALUE8', isin: 'NL0010661864', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'VASTN', name: 'VASTNED RETAIL', isin: 'NL0000392470', market: 'Euronext Amsterdam', sector: 'Real Estate' },
  { symbol: 'VVP', name: 'VIVORYON THERAP.', isin: 'DE0007921835', market: 'Euronext Amsterdam', sector: 'Healthcare' },

  // Dual Listings & Major European Stocks Traded in Amsterdam
  { symbol: 'AIR', name: 'AIRBUS', isin: 'NL0000235190', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'STLAM', name: 'STELLANTIS', isin: 'NL00150001Q9', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'STMPA', name: 'STMICROELECTRONICS', isin: 'NL0000226223', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'MT', name: 'ARCELORMITTAL', isin: 'LU1598757687', market: 'Euronext Amsterdam', sector: 'Materials' },
  { symbol: 'MC', name: 'LVMH', isin: 'FR0000121014', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'OR', name: 'LOREAL', isin: 'FR0000120321', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'RMS', name: 'HERMES', isin: 'FR0000052292', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'KER', name: 'KERING', isin: 'FR0000121485', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'TTE', name: 'TOTALENERGIES', isin: 'FR0000120271', market: 'Euronext Amsterdam', sector: 'Energy' },
  { symbol: 'SAN', name: 'SANOFI', isin: 'FR0000120578', market: 'Euronext Amsterdam', sector: 'Healthcare' },
  { symbol: 'SU', name: 'SCHNEIDER ELECT.', isin: 'FR0000121972', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'AI', name: 'AIR LIQUIDE', isin: 'FR0000120073', market: 'Euronext Amsterdam', sector: 'Materials' },
  { symbol: 'DG', name: 'VINCI', isin: 'FR0000125486', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'CS', name: 'AXA', isin: 'FR0000120628', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'BNP', name: 'BNP PARIBAS', isin: 'FR0000131104', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'BN', name: 'DANONE', isin: 'FR0000120644', market: 'Euronext Amsterdam', sector: 'Consumer Staples' },
  { symbol: 'SAF', name: 'SAFRAN', isin: 'FR0000073272', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'SGO', name: 'SAINT GOBAIN', isin: 'FR0000125007', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'SAP', name: 'SAP', isin: 'DE0007164600', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'SIE', name: 'SIEMENS', isin: 'DE0007236101', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'BMW', name: 'BMW', isin: 'DE0005190003', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'DTE', name: 'DEUTSCHE TELEKOM', isin: 'DE0005557508', market: 'Euronext Amsterdam', sector: 'Telecommunications' },
  { symbol: 'DPW', name: 'DEUTSCHE POST', isin: 'DE0005552004', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'DBK', name: 'DEUTSCHE BANK', isin: 'DE0005140008', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'IFX', name: 'INFINEON', isin: 'DE0006231004', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'BAS', name: 'BASF', isin: 'DE000BASF111', market: 'Euronext Amsterdam', sector: 'Materials' },
  { symbol: 'BAYN', name: 'BAYER', isin: 'DE000BAY0017', market: 'Euronext Amsterdam', sector: 'Healthcare' },
  { symbol: 'ADS', name: 'ADIDAS', isin: 'DE000A1EWWW0', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'ALV', name: 'ALLIANZ', isin: 'DE0008404005', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'MUV2', name: 'MUNCHENER RUCK', isin: 'DE0008430026', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'VOW3', name: 'VOLKSWAGEN', isin: 'DE0007664039', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'DHER', name: 'DELIVERY HERO', isin: 'DE000A2E4K43', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'HFG', name: 'HELLO FRESH', isin: 'DE000A161408', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'ZAL', name: 'ZALANDO', isin: 'DE000ZAL1111', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'BOUY', name: 'BOUYGUES', isin: 'FR0000120503', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'CAP', name: 'CAPGEMINI', isin: 'FR0000125338', market: 'Euronext Amsterdam', sector: 'Technology' },
  { symbol: 'ORAN', name: 'ORANGE', isin: 'FR0000133308', market: 'Euronext Amsterdam', sector: 'Telecommunications' },
  { symbol: 'PUB', name: 'PUBLICIS GROUPE', isin: 'FR0000130577', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
  { symbol: 'GLE', name: 'SOCIETE GENERALE', isin: 'FR0000130809', market: 'Euronext Amsterdam', sector: 'Financials' },
  { symbol: 'TEP', name: 'TELEPERFORMANCE', isin: 'FR0000051807', market: 'Euronext Amsterdam', sector: 'Industrials' },
  { symbol: 'ENGI', name: 'ENGIE', isin: 'FR0010208488', market: 'Euronext Amsterdam', sector: 'Utilities' },
  { symbol: 'VIV', name: 'VIVENDI', isin: 'FR0000127771', market: 'Euronext Amsterdam', sector: 'Consumer Discretionary' },
];

export class EuronextService {
  static getCompanies(): Company[] {
    return EURONEXT_AMSTERDAM_COMPANIES;
  }

  static searchCompanies(query: string): Company[] {
    const q = query.toLowerCase();
    return EURONEXT_AMSTERDAM_COMPANIES.filter(c => 
      c.name.toLowerCase().includes(q) || 
      c.symbol.toLowerCase().includes(q) ||
      c.isin.toLowerCase().includes(q)
    );
  }
}
